KVM: Move binary stats helpers to header to effectively export them
Move kvm_stats_linear_hist_update() and kvm_stats_log_hist_update() to
kvm_host.h as static inline helpers to resolve a linker error on PPC,
which references the latter from module code.  This also fixes a goof
where the functions are tagged as "inline", despite being externs and
thus not inline-friendy.

  ERROR: modpost: ".kvm_stats_log_hist_update" [arch/powerpc/kvm/kvm-hv.ko] undefined!

Fixes: c8ba95948182 ("KVM: stats: Support linear and logarithmic histogram statistics")
Cc: Jing Zhang <jingzhangos@google.com>
Signed-off-by: Sean Christopherson <seanjc@google.com>