KVM: Fix build error on s390 due to kvm_flush_shadow_all() being hidden
Hoist kvm_flush_shadow_all() out of the #ifdef block that depends on the
mmu_notifier being enabled and wanted by KVM.  KVM s390 doesn't utilize
the mmu_notifier, and so the direct call to kvm_flush_shadow_all() in
vm_destroy() rightly complains.

virt/kvm/kvm_main.c: In function ‘kvm_destroy_vm’:
virt/kvm/kvm_main.c:1248:9: error: implicit declaration of function ‘kvm_flush_shadow_all’;
did you mean ‘kvm_arch_flush_shadow_all’? [-Werror=implicit-function-declaration]
 1248 |         kvm_flush_shadow_all(kvm);
      |         ^~~~~~~~~~~~~~~~~~~~
      |         kvm_arch_flush_shadow_all

Fixes: b56a4ff6bff3 ("KVM: SEV: add cache flush to solve SEV cache incoherency issues")
Cc: stable@vger.kernel.org
Cc: Mingwei Zhang <mizhang@google.com>
Signed-off-by: Sean Christopherson <seanjc@google.com>